language: python
matrix:
  include:
    - python: "3.8"
      dist: xenial
      sudo: required
    - python: "3.8"
      arch: arm64
      dist: xenial
      sudo: required

script:
  - pip install -r requirements.txt
  # pytest --verbose -s  (print stdouts, etc.)
  - PYTEST_ADDOPTS="-s" python setup.py test
  - pip install .
